version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coupon-app
    ports:
      - "${SPRING_PORT}:8080"
    depends_on:
      - mongo
      - redis
    env_file:
      - .env

  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"  # sin 127.0.0.1
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
