version: '3.8'

networks:
  app-network:
    driver: bridge
services:
  app:
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2g
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coupon-app
    ports:
      - "${SPRING_PORT}:8080"
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    networks:
      - app-network

  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  mongo_data:
  redis_data:
